# This is a basic workflow to help you get started with Actions

name: Create

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AK }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SAK }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - name: Initialize terraform
        run: terraform init

      - name: Fmt terraform
        run: terraform fmt

      - name: Apply terraform
        run: terraform apply -auto-approve
